apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-namespace
type: Opaque
data:
  DB_USER: cHJvZHVzZXI=         # base64 of "produser"
  DB_PASSWORD: cHJvZHBhc3N3b3Jk # base64 of "prodpassword"
