apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-namespace
type: Opaque
data:
  DB_USER: ZGV2dXNlcg==         # base64 of "devuser"
  DB_PASSWORD: ZGV2cGFzc3dvcmQ= # base64 of "devpassword"
